<?php
/**
 * @file
 * Implements Cielo's payment web service for use with Drupal Commerce.
 */

// Break down the file into file blocks for better maintanance.
include_once 'commerce_cielo.admin.inc';
include_once 'commerce_cielo.checkout.form.inc';

/**
 * Implements hook_init().
 */
function commerce_cielo_init () {
  if (!libraries_get_path('brazilcards-lib')) {
    drupal_set_message(t('Cielo library is not installed.'), 'error');
  }
  else {
    $cielo_class_file = drupal_realpath(libraries_get_path('brazilcards-lib')) . '/Cielo.class.php';
    // Check if Cielo library is installed.
    if (file_exists($cielo_class_file)) {
      include_once $cielo_class_file;
    }
    else {
      drupal_set_message(t('Cielo library is not properly installed. The file @file does not exist.', array('@file', $cielo_class_file)), 'error');
    }
  }
}

/**
 * Determines access to the prior authorization capture form for Cielo Payment
 * Method.
 *
 * @param Object $order
 *   The order the transaction is on.
 * @param Object $transaction
 *   The payment transaction object to be captured.
 *
 * @return boolean
 *   TRUE or FALSE indicating capture access.
 */
function commerce_cielo_capture_access($order, $transaction) {
  // Return FALSE if the transaction isn't for Cielo or isn't
  // Awaiting capture.
  if ($transaction->payment_method != 'cielo' || $transaction->remote_status != 'authorization_only') {
    return FALSE;
  }

  // Return FALSE if it is more than 5 days past the original authorization.
  if (time() - $transaction->created > 86400 * 5) {
    return FALSE;
  }

  // Allow access if the user can update payments on this order.
  return commerce_payment_transaction_access('update', $order, $transaction);
}

/**
 * Determines access to the payment cancelation form for Cielo Payment Method.
 *
 * @param Object $order
 *   The order the transaction is on.
 * @param Object $transaction
 *   The payment transaction object to be voided.
 *
 * @return boolean
 *   TRUE or FALSE indicating voiding access.
 */
function commerce_cielo_void_access($order, $transaction) {
  // Return FALSE if the transaction isn't for Cielo or isn't
  // capture.
  if ($transaction->payment_method != 'cielo' || $transaction->remote_status != COMMERCE_PAYMENT_STATUS_SUCCESS) {
    return FALSE;
  }

  // Return FALSE if it is not the same day as the transaction was captured.
  if (time() - $transaction->created > 86400) {
    return FALSE;
  }

  // Allow access if the user can update payments on this order.
  return commerce_payment_transaction_access('update', $order, $transaction);
}

/**
 * Implements hook_menu().
 */
function commerce_cielo_menu() {
  $items = array();
  // Add a page for concluding the payment process after returning from Cielo.
  $items['checkout/%commerce_order/payment/cielo'] = array(
    'page callback' => 'commerce_cielo_redirect_back',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/commerce_cielo.router.inc',
  );

  // Add a menu item for capturing authorizations.
  $items['admin/commerce/orders/%commerce_order/payment/%commerce_payment_transaction/cielo-capture'] = array(
    'title' => 'Capture',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_cielo_capture_form', 3, 5),
    'access callback' => 'commerce_cielo_capture_access',
    'access arguments' => array(3, 5),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'context' => MENU_CONTEXT_INLINE,
    'weight' => 2,
    'file' => 'includes/commerce_cielo.admin.inc',
  );

  // Add a menu item for voiding captured transactions.
  $items['admin/commerce/orders/%commerce_order/payment/%commerce_payment_transaction/cielo-void'] = array(
    'title' => 'Void',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_cielo_void_form', 3, 5),
    'access callback' => 'commerce_cielo_void_access',
    'access arguments' => array(3, 5),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'context' => MENU_CONTEXT_INLINE,
    'weight' => 2,
    'file' => 'includes/cielo.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_commerce_payment_method_info().
 */
function commerce_cielo_commerce_payment_method_info() {
  $payment_methods = array();

  $payment_methods['cielo'] = array(
    'base' => 'commerce_cielo',
    'title' => t('Cielo'),
    'short_title' => t('Cielo Webservices'),
    'display_title' => t('By Credit or Debit Card.'),
    'description' => t("Integration with Cielo's webservice."),
  );

  return $payment_methods;
}

/**
 * Helper function for gerenating a list of options for Installment field.
 *
 * Brazilian Real currency Only.
 */
function commerce_cielo_installment_options($po_total, $max_installments) {
  for ($i = 1; $i <= $max_installments; $i++) {
    if ($i == 1) {
      $options[$i] = t('Single pay out');
    }
    else {
      // TODO: Create a hook of something or perhaps add some fine-grained
      // settings that allow interest rates to be applied on pre-set conditions.
      $installment_amount = number_format(($po_total / 100) / $i, 2, ',', '.');
      $options[$i] = t('@parcelax @valor  |  with No interest', array('@parcela' => $i, '@valor' => $installment_amount));
    }
  }
  return $options;
}

/**
 * Define a status state based on the status code returned from de remote
 * webservice.
 *
 * @param boolean $authenticate
 *   A admin setting option for whether or not the card holder
 *   ownership should had been authenticated.
 * @param string $status
 *   The status code returned from the remote server.
 *
 * @return string
 *   One of the order states defined by commerce.
 *
 * Status code descriptions are
 * // PENDING
 * 0 == Transaction was created
 * 1 == In progress
 * 2 == Authenticated
 * 3 == Not Authenticated  // if authentication was not requested
 * 4 == Authorized or still to be Captured
 * 10 == Being Authenticated
 *
 * // SUCCESS
 * 6 == Captured
 *
 * // FAILURE
 * 3 == Not Authenticated  // if authentication was requested
 * 5 == Authorization was denied
 * 8 == Not Captured
 *
 *
 * // wont happen in this context.
 * 9 == Voided
 */
function commerce_cielo_get_status_state($authenticate, $status) {
  if ($authenticate) {
    $pending = array(
      Cielo::CIELO_TRANSACTION_CREATED,
      Cielo::CIELO_IN_PROGRESS,
      Cielo::CIELO_AUTHENTICATED,
      Cielo::CIELO_AUTHORIZED,
      Cielo::CIELO_BEING_AUTHENTICATED,
    );
    $failure = array(
      // It has been explicit set that card holder must be authenticated.
      Cielo::CIELO_NOT_AUTHENTICATED,
      Cielo::CIELO_AUTHORIZATION_DENIED,
      Cielo::CIELO_NOT_CAPTURED,
    );
  }
  else {
    $pending = array(
      Cielo::CIELO_TRANSACTION_CREATED,
      Cielo::CIELO_IN_PROGRESS,
      Cielo::CIELO_AUTHENTICATED,
      // Even if authentication fails, it still might be possible to get an
      // authorization and thereafter a capturing.
      Cielo::CIELO_NOT_AUTHENTICATED,
      Cielo::CIELO_AUTHORIZED,
      Cielo::CIELO_BEING_AUTHENTICATED,
    );
    $failure = array(
      Cielo::CIELO_AUTHORIZATION_DENIED,
      Cielo::CIELO_NOT_CAPTURED,
    );
  }

  $status_code = array(
    'PENDING' => $pending,
    'SUCCESS' => array(Cielo::CIELO_CAPTURED),
    'FAILURE' => $failure,
  );

  // Set default value for when $status might come with an error code instead of
  // a status code.
  $status_state = 'FAILURE';

  // Search for a match.
  foreach ($status_code as $state => $codes) {
    if (in_array($status, $codes)) {
      $status_state = $state;
      break;
    }
  }

  // Apply the constant value set by the payment module for the given state.
  switch ($status_state) {
    case 'PENDING':
      $status_state = COMMERCE_PAYMENT_STATUS_PENDING;
      break;

    case 'SUCCESS':
      $status_state = COMMERCE_PAYMENT_STATUS_SUCCESS;
      break;

    case 'FAILURE':
      $status_state = COMMERCE_PAYMENT_STATUS_FAILURE;
      break;
  }

  return $status_state;
}

/**
 * Saves the payment transaction after each call to the remote Webservice.
 *
 * @param object $Cielo
 *   The object from the external library class
 * @param object $transaction
 *   The payment transaction object
 * @param Boolean $authenticate
 *   Whether or not the card holder shold be authenticated.
 * @param string $remote_status
 *   When no value is passed (default == empty) it will be automatically
 *   determined.
 *   The possible values for remote status are:
 *
 *   pending, failure or success (same as the transaction status) or
 *
 *   redirected          - There was a redirection to Cielo
 *   authorization_only  - Transaction was successfully authorized and is
 *                         awaiting for manual capturing at the store backend.
 */
function commerce_cielo_save_transaction($Cielo, $transaction, $authenticate, $remote_status = '') {
  $remote_id = '';
  if (isset($Cielo->response['tid'])) {
    $remote_id = check_plain($Cielo->response['tid']);
  }

  $status = '';
  $message = '';

  if (isset($Cielo->response['status'])) {
    // No transaction errors have occured.
    $status = check_plain($Cielo->response['status']);
    $message = t('Status Code: %code', array('%code' => $status));

    if (isset($Cielo->response['url-autenticacao'])) {
      $message .= t("<br />Waiting: Buyer was redirected to Cielo.");
      $remote_status = 'redirected';
    }

    foreach ($Cielo->response as $process => $values) {
      if (is_array($values)) {
        // Payment tab message.
        if (key_exists('mensagem', $values)) {
          // Assemble payment tab message.
          $message .= '<br />' . check_plain(t("$process: @message", array('@message' => check_plain($values['mensagem']))));
        }
      }
    }
  }
  elseif (isset($Cielo->response['codigo'])) {
    // The remote server reported an error.
    $status = check_plain($Cielo->response['codigo']);
    $message = t('Error Code: %code', array('%code' => $status));
    $message .= '<br />' . t('Error Message: %message', array('%message' => check_plain(t($Cielo->response['mensagem']))));
  }

  $transaction->remote_id = $remote_id;
  $transaction->remote_status = empty($remote_status) ? commerce_cielo_get_status_state($authenticate, $status) : $remote_status;
  $transaction->status = commerce_cielo_get_status_state($authenticate, $status);
  $transaction->message = $message;
  $transaction->payload[REQUEST_TIME] = $Cielo->response;

  // Save the transaction.
  commerce_payment_transaction_save($transaction);
}

/**
 * Helper function
 * It includes the external library class file and set the commom
 * arguments used for instantiating the webservice object.
 *
 * @param array $payment_method
 *   The payment settings array
 * @param string $order_number
 *   The order number
 * @param string $order_amount
 *   The order amount
 *
 * @return array
 *   Array of commom arguments
 */
function commerce_cielo_get_arguments($payment_method, $order_number, $order_amount) {

  if ($payment_method['settings']['is_test']) {
    // This is a test enviroment so we set the credentials empty.
    $payment_method['settings']['credentials']['affiliation'] = '';
    $payment_method['settings']['credentials']['token'] = '';
  }

  $arguments = array(
    'is_test' => $payment_method['settings']['is_test'],
    // These are the credentials for the production enviroment. They are ignored
    // when 'is_test' == TRUE.
    'membership' => array(
      'filiacao' => $payment_method['settings']['credentials']['affiliation'],
      'chave' => $payment_method['settings']['credentials']['token'],
    ),
    // Purchase order details.
    'order' => array(
      'pedido' => $order_number,
      'TotalAmount' => $order_amount,
    ),
    'payment' => array(),
  );

  return $arguments;
}

/**
 * Callback function for applying the t() function on the values of an array.
 *
 * @param Array $array
 *   The array that needs its values to be translatable.
 */
function commerce_cielo_t($array) {
  foreach ($array as $key => $value) {
    $array[$key] = t($value);
  }
  return $array;
}

/**
 * Check for warnings that might have been issued by the external library
 * (Brazilcards) and save them in to the watchdog log.
 *
 * @param Object $Cielo
 *   The instantiated object from the external library class.
 */
function commerce_cielo_log_watch_dog($Cielo) {
  if (!empty($Cielo->warnings)) {
    // Record it in the watch dog log.
    foreach ($Cielo->warnings as $error => $error_message) {
      if (is_array($error_message)) {
        foreach($error_message as $error_delta_message) {
          watchdog('library_brazilcards', $error . ': ' . $error_delta_message, array(), WATCHDOG_DEBUG);
        }
      }
      else {
        watchdog('library_brazilcards', $error . ': ' . $error_message, array(), WATCHDOG_DEBUG);
      }
    }
    // Clear up the object property.
    $Cielo->warnings = array();
  }
}
