<?php

/**
 * @file
 * Implements Cielo Off-site Checkout in Drupal Commerce checkout.
 */

/**
 * Implements hook_commerce_payment_method_info().
 */
function commerce_cielo_offsite_commerce_payment_method_info() {
  $payment_methods = array();

  $payment_methods['cielo_offsite'] = array(
    'base' => 'commerce_cielo_offsite',
    'title' => t('Cielo Checkout | Off-site'),
    'short_title' => t('Cielo Checkout'),
    'display_title' => t('By Credit or Debit Card.'),
    'description' => t("Cielo Checkout ( Redirects to Cielo )."),
    'terminal' => FALSE,
    'offsite' => TRUE,
	// We gotta first request cielo for a transation id and then redirect the
	// customer.
    'offsite_autoredirect' => FALSE,
  );

  return $payment_methods;
}
